# Generated by Django 3.2.5 on 2021-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('thumb_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
